-- Run this in the Supabase SQL editor to set up the schema.

-- ── Tables ─────────────────────────────────────────────────────────────────

create table if not exists rooms (
  id             uuid primary key default gen_random_uuid(),
  code           text unique not null,
  host_id        text not null,           -- player.id of the host (no FK to avoid circular dep)
  status         text not null default 'waiting',  -- waiting | playing | voting | finished
  word           text,                    -- revealed to everyone at end
  imposter_word  text,                    -- revealed to everyone at end
  imposter_id    text,                    -- revealed to everyone at end
  voted_out_id   text,                    -- player.id who got the most votes
  created_at     timestamptz default now()
);

create table if not exists players (
  id             text primary key,        -- UUID generated by the client (stored in localStorage)
  room_id        uuid references rooms(id) on delete cascade,
  name           text not null,
  is_host        boolean default false,
  has_seen_word  boolean default false,
  has_voted      boolean default false,
  joined_at      timestamptz default now(),
  unique (room_id, name)
);

-- Sensitive: never exposed to anon key — backend service key only
create table if not exists player_secrets (
  player_id   text primary key references players(id) on delete cascade,
  word        text not null,
  is_imposter boolean default false,
  vote        text                         -- player.id they voted for
);


-- ── Row-level security ──────────────────────────────────────────────────────

alter table rooms          enable row level security;
alter table players        enable row level security;
alter table player_secrets enable row level security;

-- rooms: anyone can read; only service role writes (via Flask)
create policy "rooms_select"  on rooms  for select using (true);

-- players: anyone can read; only service role writes
create policy "players_select" on players for select using (true);

-- player_secrets: NO access for anon — service role only bypasses RLS
-- (no policies needed; with RLS on and no policy, anon gets nothing)


-- ── Realtime ────────────────────────────────────────────────────────────────

-- Enable realtime for the two public tables (run from Dashboard → Database → Replication
-- or uncomment below if your Supabase version supports it via SQL):
--
-- alter publication supabase_realtime add table rooms;
-- alter publication supabase_realtime add table players;


-- ── Atomic phase-transition functions ──────────────────────────────────────
-- These prevent race conditions when multiple clients fire the same trigger.

create or replace function try_start_voting(p_code text)
returns boolean
language plpgsql security definer
as $$
declare
  v_room_id uuid;
  v_not_ready int;
begin
  select id into v_room_id
    from rooms where code = p_code and status = 'playing';
  if v_room_id is null then return false; end if;

  select count(*) into v_not_ready
    from players where room_id = v_room_id and not has_seen_word;

  if v_not_ready = 0 then
    update rooms set status = 'voting'
      where id = v_room_id and status = 'playing';
    return found;
  end if;

  return false;
end;
$$;


create or replace function try_finish_game(p_code text)
returns boolean
language plpgsql security definer
as $$
declare
  v_room_id    uuid;
  v_not_voted  int;
  v_voted_out  text;
begin
  select id into v_room_id
    from rooms where code = p_code and status = 'voting';
  if v_room_id is null then return false; end if;

  select count(*) into v_not_voted
    from players where room_id = v_room_id and not has_voted;

  if v_not_voted = 0 then
    select vote into v_voted_out
      from player_secrets
      where player_id in (select id from players where room_id = v_room_id)
        and vote is not null
      group by vote
      order by count(*) desc
      limit 1;

    update rooms
      set status = 'finished', voted_out_id = v_voted_out
      where id = v_room_id and status = 'voting';
    return found;
  end if;

  return false;
end;
$$;
